### ISSUE TITLE
Correct Constraints

### ISSUE THREAD

**Issue by ArifADS** [Vmlweb/VLBanner#1]
Hi, How should I configure this custom view constraints so it resizes accordingly? i want this view to be between the bottom of a TableView and the Tab Bar, I know this sets their frames automatically, but the constraints?

**Comment by VictorLeach96** [comment]
I've added an Example to the repo to show you how I achieved this.

**Comment by ArifADS** [comment]
Excellent, another question, I don't know if i have to do another Issue, but, can i delete this lines so I don't need SwiftCript?

``` swift
if let md5Device = ASIdentifierManager.sharedManager().advertisingIdentifier.UUIDString.md5(){
request.testDevices.append(md5Device)
}
```

**Comment by VictorLeach96** [comment]
Yep you can remove that and SwiftCrypt along with it.
Though it means AdMob will always delivery production adverts to non-simulator devices.
